import Header from "@/components/Header";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ssoon blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <section className="pt-20 w-full h-full flex flex-col min-h-screen">
          <Header />
          <div className="flex-1 w-full mx-auto max-w-3xl min-h-full px-5">
            <main className="h-full">{children}</main>
          </div>
          <Footer />
        </section>
      </body>
    </html>
  );
}
