import Header from '@/components/Header';
import '../styles/globals.css';
import type { Metadata } from 'next';
import Footer from '@/components/Footer';
import { pretendard } from '@/lib/fonts';
import AppProviders from './AppProviders';

export const metadata: Metadata = {
  title: 'Ssoon blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={pretendard.className} suppressHydrationWarning>
      <body className="bg-white dark:bg-slate-900 transition-[background]">
        <AppProviders>
          <section className="pt-20 w-full h-full flex flex-col min-h-screen">
            <Header />
            <div className="flex-1 w-full mx-auto max-w-3xl min-h-full px-5">
              <main className="h-full">{children}</main>
            </div>
            <Footer />
          </section>
        </AppProviders>
      </body>
    </html>
  );
}
